'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const P=require('../lib/signal-paper');
const CG=require('../lib/coingecko');
const t=1800000000000;
const factors=Object.fromEntries(['trend','macd','rsi','boll','anchor','stable','robust','edge'].map(k=>[k,true]));
const signal=(at=t,extra={})=>({coinId:'bitcoin',symbol:'BTC',label:'BUY',grade:'A+',observedPrice:100,observedAt:at,factors,...extra});
const quote=(at=t,extra={})=>({coinId:'bitcoin',price:100,asOf:at,source:'live',status:'fresh',...extra});
function entry(s){assert.equal(P.execute(s,signal(),quote(),t).reason,'awaiting-confirmation');assert.equal(P.execute(s,signal(t+60000),quote(t+60000),t+60000).ok,true);}
test('confirmed entry is bounded, idempotent and independent of holdings',()=>{const s={portfolio:[{quantity:9}]};entry(s);assert.equal(s.signalPositions.length,1);assert.equal(s.signalLedger.length,1);assert.equal(s.portfolio[0].quantity,9);assert.equal(P.execute(s,signal(t+60000),quote(t+60000),t+60000).reason,'already-seen');assert.equal(s.signalPositions[0].quantity*s.signalPositions[0].entryPrice,100);});
test('weak observation interrupts confirmation',()=>{const s={};P.execute(s,signal(),quote(),t);P.observe(s,signal(t+30000,{grade:'C',label:'NEU'}),t+30000);assert.equal(P.execute(s,signal(t+60000),quote(t+60000),t+60000).reason,'awaiting-confirmation');assert.equal(s.signalPositions.length,0);});
test('unsafe quotes and stale signals never fill',()=>{for(const q of [quote(t,{source:'simulation'}),quote(t,{coinId:'ethereum'}),quote(t-1),quote(t,{price:103}),quote(t,{status:'stale'})]){const s={};assert.equal(P.execute(s,signal(),q,t).ok,false);assert.equal(s.signalLedger.length,0);}assert.equal(P.validSignal(signal(t-300001),t),false);assert.equal(P.validSignal(signal(t,{grade:'A'}),t),false);});
test('stop checks require matching post-entry live quote and close once',()=>{const s={};entry(s);assert.equal(P.checkStops(s,{bitcoin:quote(t+120000,{coinId:'ethereum',price:80})},t+120000).length,0);assert.equal(P.checkStops(s,{bitcoin:quote(t+120000,{price:80})},t+120000).length,1);assert.equal(P.checkStops(s,{bitcoin:quote(t+120000,{price:80})},t+120000).length,0);assert.equal(s.signalLedger.length,2);assert.equal(s.signalLedger[1].price,79.92);});
test('opposite confirmed signal closes, cooldown prevents immediate re-entry',()=>{const s={};entry(s);assert.equal(P.execute(s,signal(t+120000,{label:'SELL'}),quote(t+120000),t+120000).ok,true);assert.equal(P.execute(s,signal(t+180000),quote(t+180000),t+180000).reason,'cooldown');});
test('conflicting queued observations cancel rather than pick a direction',()=>{const s={};P.observe(s,signal(),t);P.observe(s,signal(t,{label:'SELL'}),t);assert.equal(s.signalQueue.length,0);});
test('provider credentials are server headers restricted to CoinGecko',async()=>{const old={demo:process.env.COINGECKO_DEMO_API_KEY,pro:process.env.COINGECKO_PRO_API_KEY};try{delete process.env.COINGECKO_PRO_API_KEY;process.env.COINGECKO_DEMO_API_KEY='demo-test';const calls=[];const fetcher=CG.authenticatedFetch(async(...args)=>calls.push(args));await fetcher('https://api.coingecko.com/api/v3/global');assert.equal(calls[0][1].headers['x-cg-demo-api-key'],'demo-test');process.env.COINGECKO_PRO_API_KEY='pro-test';await fetcher('https://api.coingecko.com/api/v3/global');assert.match(calls[1][0],/^https:\/\/pro-api/);assert.equal(calls[1][1].headers['x-cg-pro-api-key'],'pro-test');await fetcher('https://api.alternative.me/fng/');assert.equal(calls[2][1].headers,undefined);}finally{for(const [key,value] of [['COINGECKO_DEMO_API_KEY',old.demo],['COINGECKO_PRO_API_KEY',old.pro]]){if(value===undefined)delete process.env[key];else process.env[key]=value;}}});
